// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFGAUSqoR7zZplyVhL04Cy-d0vSe3rSNw',
    appId: '1:709154181716:web:6fb883093380bc7d2013c1',
    messagingSenderId: '709154181716',
    projectId: 'mrmauth',
    authDomain: 'mrmauth.firebaseapp.com',
    databaseURL: 'https://mrmauth-default-rtdb.firebaseio.com',
    storageBucket: 'mrmauth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3q5qDwR38n-dYGfkDfM5TVxzrN1lEvBA',
    appId: '1:709154181716:android:d1b5fd1473949c322013c1',
    messagingSenderId: '709154181716',
    projectId: 'mrmauth',
    databaseURL: 'https://mrmauth-default-rtdb.firebaseio.com',
    storageBucket: 'mrmauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkjZC-PWwnj0h6s7ESuEfgTvtY3wS_IwY',
    appId: '1:709154181716:ios:e0450f04c1cfdb202013c1',
    messagingSenderId: '709154181716',
    projectId: 'mrmauth',
    databaseURL: 'https://mrmauth-default-rtdb.firebaseio.com',
    storageBucket: 'mrmauth.appspot.com',
    iosClientId: '709154181716-ugrr6gmsh5ntnoaqbvht9fhvia17cq8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkjZC-PWwnj0h6s7ESuEfgTvtY3wS_IwY',
    appId: '1:709154181716:ios:e0450f04c1cfdb202013c1',
    messagingSenderId: '709154181716',
    projectId: 'mrmauth',
    databaseURL: 'https://mrmauth-default-rtdb.firebaseio.com',
    storageBucket: 'mrmauth.appspot.com',
    iosClientId: '709154181716-ugrr6gmsh5ntnoaqbvht9fhvia17cq8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
